import type { MetadataRoute } from "next";

/**
 * PWA manifest. Next.js serves this at `/manifest.webmanifest` and injects
 * the right `<link rel="manifest">` tag in the root layout.
 *
 * Icons are referenced from two sources:
 *
 *   1. Real static PNGs under `public/icons/` — required by Lighthouse PWA
 *      installability + Chrome's add-to-home-screen UI. Generated by
 *      `scripts/generate-icons.mjs` (espresso bg, ivory "I", ink "H").
 *
 *   2. The dynamic `src/app/icon.tsx` and `src/app/apple-icon.tsx` routes —
 *      kept for the browser tab favicon and `<link rel="apple-touch-icon">`
 *      tag, which Next.js injects automatically.
 *
 * Both can coexist. The manifest only consults the PNG list; the dynamic
 * routes serve the favicon outside the manifest.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Inglés Hotelero",
    short_name: "Inglés Hotelero",
    description:
      "Evaluación y capacitación de inglés para equipos hoteleros en Latinoamérica.",
    lang: "es-MX",
    dir: "ltr",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#F5F0E6",
    theme_color: "#2B1D14",
    categories: ["education", "business", "productivity"],
    icons: [
      // Real PNG icons — Lighthouse + Chromium installability.
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/apple-touch-icon.png",
        sizes: "180x180",
        type: "image/png",
      },
      // Dynamic routes — Next.js auto-injects these for the browser tab
      // favicon and apple-touch-icon link tags. Declared here so the
      // manifest also lists them as fallback options.
      {
        src: "/icon",
        sizes: "any",
        type: "image/png",
      },
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
