import type { MetadataRoute } from "next";

/**
 * PWA manifest. Next.js serves this at `/manifest.webmanifest` and injects
 * the right `<link rel="manifest">` tag in the root layout.
 *
 * Icons are referenced from two sources:
 *
 *   1. Real static PNGs under `public/icons/` — required by Lighthouse PWA
 *      installability + Chrome's add-to-home-screen UI. Generated by
 *      `scripts/generate-icons.mjs` (espresso bg, ivory "I", ink "H").
 *
 *   2. The static `src/app/icon.png` and `src/app/apple-icon.png` files —
 *      Next 14 auto-injects these as `<link rel="icon" href="/icon.png">`
 *      and `<link rel="apple-touch-icon" href="/apple-icon.png">` so the
 *      browser tab favicon Just Works without us touching the layout.
 *
 * Both can coexist. The manifest consults only the PNG list below; the
 * src/app/icon.png file serves the favicon outside the manifest.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Inglés Hotelero",
    short_name: "Inglés Hotelero",
    description:
      "Evaluación y capacitación de inglés para equipos hoteleros en Latinoamérica.",
    lang: "es-MX",
    dir: "ltr",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#F5F0E6",
    theme_color: "#2B1D14",
    categories: ["education", "business", "productivity"],
    icons: [
      // Real PNG icons — Lighthouse + Chromium installability.
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/apple-touch-icon.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
